openapi: 3.0.0
info:
  title: FilesAnalysis API
  version: 1.0.0
  description: API для управления анализом файлов

servers:
  - url: http://localhost:8008
    description: Локальный сервер для разработки

paths:
  /file/{id}/words_cloud:
    get:
      summary: Получение урла на облако слов по id файла
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор файла
      responses:
        '200':
          description: Облако слов успешно получено
        '404':
          description: Файл не найден
        '500':
          description: Ошибка при чтении файла

  /file/{id}/analysis:
    post:
      summary: Получение урла на файл анализа по id файла
      parameters:
          - name: id
            in: path
            required: true
            schema:
                type: string
            description: Идентификатор файла
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Файл для анализа
      responses:
          '200':
            description: Файл успешно проанализирован
          '500':
            description: Ошибка при чтении файла