services:
  homework:
    build:
      context: ./homework
      dockerfile: Dockerfile
    networks:
      - main
    depends_on:
      - finance_tracker_db

  finance_tracker_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: database
      POSTGRES_PASSWORD: database
      POSTGRES_DB: finance_tracker
    networks:
      - main

networks:
  main:
    driver: bridge