openapi: 3.0.0
info:
  title: OrdersService API
  version: 1.0.0
  description: API сервиса заказов

servers:
  - url: http://localhost:8007
    description: Локальный сервер для разработки

paths:
  /orders/list:
    get:
      summary: Получение списка заказов
      responses:
        '200':
          description: Список заказов успешно получен
        '404':
          description: У пользователя еще нет заказов (хотя по факту лучше бы 200, это же не ошибка)
        '500':
          description: Ошибка сервиса

  /orders/{id}:
    get:
      summary: Получение конкретного заказа
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Идентификатор заказа
      responses:
        '200':
          description: Информация о заказе успешно получена
        '404':
          description: Такого заказа для этого пользователя не существует
        '500':
          description: Ошибка сервиса

  /orders/create:
    post:
      summary: Загрузка файла
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: Описание заказа
                  example: Some very helpfully order description
                amount:
                  type: integer
                  description: Сумма для оплаты заказа (в рублях)
                  example: 500
                user_id:
                  type: string
                  example: d2b3ee91-6570-4ad7-9e61-f3f6d2c0ae82
              required:

      responses:
        '200':
          description: Заказ успешно создан
        '400':
          description: Неверный запрос
        '500':
          description: Внутренняя ошибка сервера